### ISSUE TITLE
Looking for rust sources in the wrong place.

### ISSUE THREAD

**Issue by Plasticcaz** [reedz/windbg-debug#2]
While I'm stepping through my code, fairly often the plugin will stop and give me a message like this:

`Unable to open 'panicking.rs': File not found (c:\projects\rust\src\libstd\panicking.rs).`

I suspect it is looking for the rust language source code. This path is likely specific to the developer of this plugin, and should be configurable by the user of the plugin.

You should also consider looking at the place that rustup installs the rust source by default, as that's where most people will have placed it.

**Comment by reedz** [comment]
Hi,

Thanks for submitting the issue!
Yeah, I've stumbled upon this issue myself and can reproduce it fairly easily.

Adding a configuration options and looking into default folder sounds rational - will do.
