### ISSUE TITLE
Specify additional PDB files.

### ISSUE THREAD

**Issue by sochka** [reedz/windbg-debug#4]
Hello,
Does this extension support specifying additional .pdb directories?
It would be very nice to have the additional option to specify list of "pdb" directories, as well as additonal source paths.
Thanks,
Sasha.

**Comment by reedz** [comment]
Hi Sasha,

Thanks for the feature request ! Indeed, it's not possible to specify pdb folders right now (though it's possible to specify source paths - please see [this configuration](https://github.com/reedz/windbg-debug/blob/master/src/windbg-debug-tests/test-debuggees/rust/.vscode/launch.json)). I'll add this functionality in the coming week, hopefully.

Regards,
Dmytro
